version: '2.1'
services:
  app:
    build:
      context: ../../../..
      dockerfile: ./docker/src/main/docker/Dockerfile
    volumes: ['app-data:/home']
    ports:
      - '5005:5005'
      - '8080:8080'
      - '9990:9990'
    networks:
      public-net:
        aliases:
          - app
    #mem_limit: 786432000 # container limit: 700Mb (700 * 1024 * 1024)
volumes:
  app-data:
networks:
  public-net:
    driver: bridge
